import { type Box, BoxTypes } from './types';

export const boxes: Box[] = [
  { id: 0, name: '开始', type: BoxTypes.Start, pids: [] },
  { id: 7, name: '史东薇尔城', type: BoxTypes.Position, pids: [{ id: 1, type: 0 }] },
  { id: 1, name: '噩兆', type: BoxTypes.Boss, pids: [{ id: 56, type: 0 }] },
  { id: 2, name: '接肢', type: BoxTypes.Boss, pids: [{ id: 7, type: 0 }] },
  { id: 3, name: '湖区', type: BoxTypes.Position, pids: [{ id: 2, type: 0 }] },
  { id: 4, name: '满月女王', type: BoxTypes.Boss, pids: [{ id: 13, type: 0 }] },
  { id: 8, name: '王城', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 5, name: '初始之王', type: BoxTypes.Boss, pids: [{ id: 8, type: 0 }] },
  { id: 6, name: '雪山', type: BoxTypes.Position, pids: [{ id: 14, type: 0 }] },
  { id: 9, name: '菈妮', type: BoxTypes.NPC, pids: [{ id: 3, type: 0 }] },
  { id: 10, name: '狮子混种', type: BoxTypes.Boss, pids: [{ id: 59, type: 0 }] },
  {
    id: 11,
    name: '拉塔恩',
    type: BoxTypes.Boss,
    pids: [
      { id: 58, type: 0 },
      { id: 12, type: 0 },
    ],
  },
  { id: 12, name: '壶哥', type: BoxTypes.NPC, pids: [{ id: 56, type: 0 }] },
  { id: 13, name: '红狼', type: BoxTypes.Boss, pids: [{ id: 3, type: 0 }] },
  { id: 14, name: '恶兆王', type: BoxTypes.Boss, pids: [{ id: 5, type: 0 }] },
  { id: 15, name: '泪滴哥', type: BoxTypes.Boss, pids: [{ id: 54, type: 0 }] },
  { id: 16, name: '英雄石像鬼', type: BoxTypes.Boss, pids: [{ id: 15, type: 0 }] },
  {
    id: 17,
    name: '死龙',
    type: BoxTypes.Boss,
    pids: [
      { id: 18, type: 0 },
      { id: 63, type: 0 },
    ],
  },
  { id: 18, name: '死眠', type: BoxTypes.NPC, pids: [{ id: 60, type: 0 }] },
  { id: 19, name: '前往巨人山顶', type: BoxTypes.Position, pids: [{ id: 14, type: 0 }] },
  { id: 20, name: '火焰巨人', type: BoxTypes.Boss, pids: [{ id: 19, type: 0 }] },
  { id: 21, name: '烧树', type: BoxTypes.Action, pids: [{ id: 20, type: 0 }] },
  { id: 22, name: '前往天空城', type: BoxTypes.Position, pids: [{ id: 21, type: 0 }] },
  { id: 23, name: '“黑剑”玛利喀斯', type: BoxTypes.Boss, pids: [{ id: 79, type: 0 }] },
  { id: 24, name: '“龙王”普拉顿桑克斯', type: BoxTypes.Boss, pids: [{ id: 79, type: 0 }] },
  { id: 25, name: '前往灰城', type: BoxTypes.Position, pids: [{ id: 23, type: 0 }] },
  { id: 26, name: '百智爵士', type: BoxTypes.Boss, pids: [{ id: 25, type: 0 }] },
  { id: 27, name: '葛德温', type: BoxTypes.Boss, pids: [{ id: 26, type: 0 }] },
  { id: 28, name: '艾尔登之兽', type: BoxTypes.Boss, pids: [{ id: 27, type: 0 }] },
  { id: 29, name: '衰颓时代', type: BoxTypes.End, pids: [{ id: 35, type: 0 }] },
  {
    id: 30,
    name: '潜藏者时代',
    type: BoxTypes.End,
    pids: [
      { id: 39, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 31,
    name: '绝望时代',
    type: BoxTypes.End,
    pids: [
      { id: 40, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 32,
    name: '律法时代',
    type: BoxTypes.End,
    pids: [
      { id: 41, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 33,
    name: '群星时代',
    type: BoxTypes.End,
    pids: [
      { id: 36, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  {
    id: 34,
    name: '癫火之王',
    type: BoxTypes.End,
    pids: [
      { id: 37, type: 0 },
      { id: 35, type: 0 },
    ],
  },
  { id: 35, name: '触碰玛莉卡', type: BoxTypes.Action, pids: [{ id: 28, type: 0 }] },
  {
    id: 36,
    name: '触碰菈妮的符文',
    type: BoxTypes.Action,
    pids: [
      { id: 67, type: 0 },
      { id: 28, type: 0 },
    ],
  },
  {
    id: 37,
    name: '拥抱癫火',
    type: BoxTypes.Action,
    pids: [
      { id: 38, type: 0 },
      { id: 78, type: 0 },
    ],
  },
  { id: 38, name: '三指女巫海妲', type: BoxTypes.NPC, pids: [{ id: 3, type: 0 }] },
  { id: 39, name: '死王子修复卢恩', type: BoxTypes.NPC, pids: [{ id: 17, type: 0 }] },
  { id: 40, name: '食粪者', type: BoxTypes.NPC, pids: [{ id: 77, type: 0 }] },
  { id: 41, name: '金面具', type: BoxTypes.NPC, pids: [{ id: 8, type: 0 }] },
  { id: 42, name: '化圣雪原', type: BoxTypes.Position, pids: [{ id: 14, type: 0 }] },
  { id: 43, name: '仪典镇', type: BoxTypes.Position, pids: [{ id: 42, type: 0 }] },
  { id: 44, name: '圣树', type: BoxTypes.Position, pids: [{ id: 43, type: 0 }] },
  { id: 45, name: '“圣树骑士”罗蕾塔', type: BoxTypes.Boss, pids: [{ id: 44, type: 0 }] },
  { id: 46, name: '玛莲妮亚', type: BoxTypes.Boss, pids: [{ id: 45, type: 0 }] },
  { id: 47, name: '老将尼奥', type: BoxTypes.Boss, pids: [{ id: 19, type: 0 }] },
  { id: 48, name: '亚坦高原', type: BoxTypes.Position, pids: [{ id: 4, type: 0 }] },
  { id: 49, name: '日荫城', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 50, name: '火山官邸', type: BoxTypes.Position, pids: [{ id: 48, type: 0 }] },
  { id: 51, name: '神皮贵族', type: BoxTypes.Boss, pids: [{ id: 50, type: 0 }] },
  { id: 52, name: '拉卡德', type: BoxTypes.Boss, pids: [{ id: 51, type: 0 }] },
  { id: 53, name: '“铁棘”艾隆梅尔', type: BoxTypes.Boss, pids: [{ id: 49, type: 0 }] },
  {
    id: 54,
    name: '永恒之城诺克隆恩',
    type: BoxTypes.Position,
    pids: [
      { id: 57, type: 0 },
      { id: 11, type: 0 },
    ],
  },
  {
    id: 55,
    name: '希芙拉河',
    type: BoxTypes.Position,
    pids: [
      { id: 57, type: 0 },
      { id: 54, type: 0 },
    ],
  },
  { id: 56, name: '宁姆格福', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 57, name: '雾林', type: BoxTypes.Position, pids: [{ id: 56, type: 0 }] },
  { id: 58, name: '盖利德', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 59, name: '啜泣半岛', type: BoxTypes.Position, pids: [{ id: 56, type: 0 }] },
  { id: 60, name: '圆桌', type: BoxTypes.Position, pids: [{ id: 0, type: 0 }] },
  { id: 61, name: '祖灵', type: BoxTypes.Boss, pids: [{ id: 55, type: 0 }] },
  { id: 62, name: '祖灵之王', type: BoxTypes.Boss, pids: [{ id: 15, type: 0 }] },
  {
    id: 63,
    name: '深根',
    type: BoxTypes.Position,
    pids: [
      { id: 78, type: 0 },
      { id: 16, type: 0 },
    ],
  },
  {
    id: 64,
    name: '安瑟尔河(下)',
    type: BoxTypes.Position,
    pids: [
      { id: 3, type: 0 },
      { id: 66, type: 0 },
    ],
  },
  { id: 66, name: '安瑟尔河(上)', type: BoxTypes.Position, pids: [{ id:75, type: 0 },{ id: 63, type: 0 }] },
  { id: 65, name: '腐败湖', type: BoxTypes.Position, pids: [{ id: 66, type: 0 }] },
  {
    id: 67,
    name: '和菈妮结婚',
    type: BoxTypes.Action,
    pids: [
      { id: 9, type: 0 },
      { id: 70, type: 0 },
    ],
  },
  { id: 68, name: '诺克史黛拉的龙人士兵', type: BoxTypes.Boss, pids: [{ id: 64, type: 0 }] },
  { id: 69, name: '黑暗弃子艾斯提', type: BoxTypes.Boss, pids: [{ id: 65, type: 0 }] },
  { id: 70, name: '月光高原', type: BoxTypes.Position, pids: [{ id: 69, type: 0 }] },
  { id: 71, name: '鲜血王朝', type: BoxTypes.Position, pids: [{ id: 42, type: 0 }] },
  { id: 72, name: '“鲜血君主”蒙格', type: BoxTypes.Boss, pids: [{ id: 71, type: 0 }] },
  { id: 73, name: '卡利亚城寨', type: BoxTypes.Position, pids: [{ id: 3, type: 0 }] },
  { id: 74, name: '禁卫骑士罗蕾塔', type: BoxTypes.Boss, pids: [{ id: 73, type: 0 }] },
  { id: 75, name: '三娣妹塔', type: BoxTypes.Position, pids: [{ id: 74, type: 0 }] },
  { id: 76, name: '恶兆之子蒙格', type: BoxTypes.Boss, pids: [{ id: 77, type: 0 }] },
  { id: 77, name: '王城下水道', type: BoxTypes.Position, pids: [{ id: 8, type: 0 }] },
  { id: 78, name: '癫火封印', type: BoxTypes.Position, pids: [{ id: 76, type: 0 }] },
  { id: 79, name: '神皮双人组', type: BoxTypes.Boss, pids: [{ id: 22, type: 0 }] },
];
